# Quanti giorni devono passare prima di ritenere l' username + IP 
# validi evitando di re-inserire la password?
sessionsTimeout: 5
# Password richiesta per accedere
password: YEET
# Vuoi eseguire l' ip-ban su chi non inserisce la password in tempo
# o la inserisce sbagliata?
RealBan: false
# Numero di secondi per inserire la passowrd
tempoMassimoAccesso: 10